float calcDelta(float a, float b, float c);
float calcRaiz(float a, float  b, float delta, char signal);
int calcQuantRaizes(float delta);
float calcVerticeX(float b, float a);
float calcVerticeY(float delta, float a);
float pedirValueFloat(char* msg);
int pedirValueInt(char* msg);
float mostrarRaizes(float a, float b, float delta);
float calcFX(float a, float b, float c, float x);
float calcFxMultiple(float a, float b, float c, int quant, int start);
